[connections.snowflake]
account = "QZSYJYT-ALB66033"
user = "YOS007"
password = "s8AHuTXYLUrpi5p"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
